# Pandas

Used for data manipulation, visualization, and building ML models, based on NumPy.

### Pandas data types: series and dataframes.
Series are like 1-dimensional dataframes. A column of a dataframe can be thought of as a series.

## create Pandas series

In [1]:
import pandas as pd

In [6]:
a = pd.Series([1,2,3,4,5])
b = pd.Series(["Hello", True, 2]) # can be heterogeneous

In [7]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
b

0    Hello
1     True
2        2
dtype: object

In [10]:
a[2] # indexing works on Series

3

In [11]:
a = pd.Series(['a', 'b', 'c'])

In [12]:
a

0    a
1    b
2    c
dtype: object

You can do dates!

In [13]:
a = pd.date_range(start = '01-01-2018', end = '23-2-2018')

In [14]:
a

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10', '2018-01-11', '2018-01-12',
               '2018-01-13', '2018-01-14', '2018-01-15', '2018-01-16',
               '2018-01-17', '2018-01-18', '2018-01-19', '2018-01-20',
               '2018-01-21', '2018-01-22', '2018-01-23', '2018-01-24',
               '2018-01-25', '2018-01-26', '2018-01-27', '2018-01-28',
               '2018-01-29', '2018-01-30', '2018-01-31', '2018-02-01',
               '2018-02-02', '2018-02-03', '2018-02-04', '2018-02-05',
               '2018-02-06', '2018-02-07', '2018-02-08', '2018-02-09',
               '2018-02-10', '2018-02-11', '2018-02-12', '2018-02-13',
               '2018-02-14', '2018-02-15', '2018-02-16', '2018-02-17',
               '2018-02-18', '2018-02-19', '2018-02-20', '2018-02-21',
               '2018-02-22', '2018-02-23'],
              dtype='datetime64[ns]', freq='D')

In [16]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

## Pandas dataframes

In [17]:
import numpy as np

In [25]:
temp = np.random.randint(low=20, high=100, size=[20,])

In [26]:
temp

array([43, 20, 68, 63, 98, 38, 78, 60, 46, 79, 70, 51, 48, 24, 79, 53, 79,
       85, 96, 91])

In [27]:
name = np.random.choice(['Abhay', 'Teclov', 'Geekshub', 'Ankit'],20)

In [28]:
name

array(['Ankit', 'Geekshub', 'Teclov', 'Ankit', 'Teclov', 'Ankit', 'Ankit',
       'Abhay', 'Ankit', 'Ankit', 'Teclov', 'Abhay', 'Abhay', 'Ankit',
       'Geekshub', 'Geekshub', 'Geekshub', 'Teclov', 'Ankit', 'Ankit'],
      dtype='<U8')

In [29]:
random = np.random.choice([10, 11, 12, 13, 14], 20)

In [30]:
random

array([12, 12, 10, 12, 14, 10, 10, 11, 11, 11, 10, 10, 13, 13, 14, 11, 12,
       13, 10, 14])

In [31]:
a = list(zip(temp, name, random))

In [32]:
a

[(43, 'Ankit', 12),
 (20, 'Geekshub', 12),
 (68, 'Teclov', 10),
 (63, 'Ankit', 12),
 (98, 'Teclov', 14),
 (38, 'Ankit', 10),
 (78, 'Ankit', 10),
 (60, 'Abhay', 11),
 (46, 'Ankit', 11),
 (79, 'Ankit', 11),
 (70, 'Teclov', 10),
 (51, 'Abhay', 10),
 (48, 'Abhay', 13),
 (24, 'Ankit', 13),
 (79, 'Geekshub', 14),
 (53, 'Geekshub', 11),
 (79, 'Geekshub', 12),
 (85, 'Teclov', 13),
 (96, 'Ankit', 10),
 (91, 'Ankit', 14)]

In [33]:
df = pd.DataFrame(data = a, columns=['temp', 'name', 'random'])

In [34]:
df

    temp      name  random
0     43     Ankit      12
1     20  Geekshub      12
2     68    Teclov      10
3     63     Ankit      12
4     98    Teclov      14
5     38     Ankit      10
6     78     Ankit      10
7     60     Abhay      11
8     46     Ankit      11
9     79     Ankit      11
10    70    Teclov      10
11    51     Abhay      10
12    48     Abhay      13
13    24     Ankit      13
14    79  Geekshub      14
15    53  Geekshub      11
16    79  Geekshub      12
17    85    Teclov      13
18    96     Ankit      10
19    91     Ankit      14

In [35]:
df = pd.DataFrame({'temp':temp, 'name': name, 'random': random})

In [36]:
df

    temp      name  random
0     43     Ankit      12
1     20  Geekshub      12
2     68    Teclov      10
3     63     Ankit      12
4     98    Teclov      14
5     38     Ankit      10
6     78     Ankit      10
7     60     Abhay      11
8     46     Ankit      11
9     79     Ankit      11
10    70    Teclov      10
11    51     Abhay      10
12    48     Abhay      13
13    24     Ankit      13
14    79  Geekshub      14
15    53  Geekshub      11
16    79  Geekshub      12
17    85    Teclov      13
18    96     Ankit      10
19    91     Ankit      14

In [37]:
df.head()

   temp      name  random
0    43     Ankit      12
1    20  Geekshub      12
2    68    Teclov      10
3    63     Ankit      12
4    98    Teclov      14

In [39]:
df.tail()

    temp      name  random
15    53  Geekshub      11
16    79  Geekshub      12
17    85    Teclov      13
18    96     Ankit      10
19    91     Ankit      14

In [41]:
df.shape

(20, 3)

In [44]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [45]:
df['name']

0        Ankit
1     Geekshub
2       Teclov
3        Ankit
4       Teclov
5        Ankit
6        Ankit
7        Abhay
8        Ankit
9        Ankit
10      Teclov
11       Abhay
12       Abhay
13       Ankit
14    Geekshub
15    Geekshub
16    Geekshub
17      Teclov
18       Ankit
19       Ankit
Name: name, dtype: object

In [46]:
df['temp']

0     43
1     20
2     68
3     63
4     98
5     38
6     78
7     60
8     46
9     79
10    70
11    51
12    48
13    24
14    79
15    53
16    79
17    85
18    96
19    91
Name: temp, dtype: int32

In [48]:
df['temp'].describe()

count    20.000000
mean     63.450000
std      22.719051
min      20.000000
25%      47.500000
50%      65.500000
75%      79.000000
max      98.000000
Name: temp, dtype: float64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   temp    20 non-null     int32
 1   name    20 non-null     object
 2   random  20 non-null     int32
dtypes: int32(2), object(1)
memory usage: 448.0+ bytes

In [51]:
df.values

array([[43, 'Ankit', 12],
       [20, 'Geekshub', 12],
       [68, 'Teclov', 10],
       [63, 'Ankit', 12],
       [98, 'Teclov', 14],
       [38, 'Ankit', 10],
       [78, 'Ankit', 10],
       [60, 'Abhay', 11],
       [46, 'Ankit', 11],
       [79, 'Ankit', 11],
       [70, 'Teclov', 10],
       [51, 'Abhay', 10],
       [48, 'Abhay', 13],
       [24, 'Ankit', 13],
       [79, 'Geekshub', 14],
       [53, 'Geekshub', 11],
       [79, 'Geekshub', 12],
       [85, 'Teclov', 13],
       [96, 'Ankit', 10],
       [91, 'Ankit', 14]], dtype=object)

In [57]:
df.set_index('temp', inplace = True) # inplace modifies df

KeyError: "None of ['temp'] are in the columns"

In [56]:
df

          name  random
temp
43       Ankit      12
20    Geekshub      12
68      Teclov      10
63       Ankit      12
98      Teclov      14
38       Ankit      10
78       Ankit      10
60       Abhay      11
46       Ankit      11
79       Ankit      11
70      Teclov      10
51       Abhay      10
48       Abhay      13
24       Ankit      13
79    Geekshub      14
53    Geekshub      11
79    Geekshub      12
85      Teclov      13
96       Ankit      10
91       Ankit      14

In [58]:
df.sort_index(axis=0, ascending=True)

          name  random
temp
20    Geekshub      12
24       Ankit      13
38       Ankit      10
43       Ankit      12
46       Ankit      11
48       Abhay      13
51       Abhay      10
53    Geekshub      11
60       Abhay      11
63       Ankit      12
68      Teclov      10
70      Teclov      10
78       Ankit      10
79    Geekshub      12
79       Ankit      11
79    Geekshub      14
85      Teclov      13
91       Ankit      14
96       Ankit      10
98      Teclov      14

In [62]:
df.sort_values(by='random', ascending=False)

          name  random
temp
91       Ankit      14
98      Teclov      14
79    Geekshub      14
85      Teclov      13
24       Ankit      13
48       Abhay      13
20    Geekshub      12
79    Geekshub      12
43       Ankit      12
63       Ankit      12
79       Ankit      11
46       Ankit      11
60       Abhay      11
53    Geekshub      11
51       Abhay      10
78       Ankit      10
38       Ankit      10
68      Teclov      10
96       Ankit      10
70      Teclov      10

In [65]:
df.drop(['random'], axis=1, inplace=True)

In [66]:
df

          name
temp
43       Ankit
20    Geekshub
68      Teclov
63       Ankit
98      Teclov
38       Ankit
78       Ankit
60       Abhay
46       Ankit
79       Ankit
70      Teclov
51       Abhay
48       Abhay
24       Ankit
79    Geekshub
53    Geekshub
79    Geekshub
85      Teclov
96       Ankit
91       Ankit

In [70]:
df = pd.DataFrame({'temp':temp, 'name': name, 'random': random})
df

    temp      name  random
0     43     Ankit      12
1     20  Geekshub      12
2     68    Teclov      10
3     63     Ankit      12
4     98    Teclov      14
5     38     Ankit      10
6     78     Ankit      10
7     60     Abhay      11
8     46     Ankit      11
9     79     Ankit      11
10    70    Teclov      10
11    51     Abhay      10
12    48     Abhay      13
13    24     Ankit      13
14    79  Geekshub      14
15    53  Geekshub      11
16    79  Geekshub      12
17    85    Teclov      13
18    96     Ankit      10
19    91     Ankit      14

In [69]:
df.iloc[[0, 1]]

   temp      name  random
0    43     Ankit      12
1    20  Geekshub      12

In [71]:
df.iloc[1:3, 1]

1    Geekshub
2      Teclov
Name: name, dtype: object

In [75]:
df.iloc[[-1]]

    temp   name  random
19    91  Ankit      14

In [76]:
df1 = pd.read_csv("weather_data.csv")

In [77]:
df1

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [80]:
# pip3 install openpyxl
df1.to_excel('df_x1.xlsx', sheet_name = 'weather_data')

In [81]:
df2 = pd.read_excel('df_x1.xlsx')

In [82]:
df2

   Unnamed: 0       day  temperature  windspeed  event
0           0  1/1/2017           32          6   Rain
1           1  1/2/2017           35          7  Sunny
2           2  1/3/2017           28          2   Snow
3           3  1/4/2017           24          7   Snow
4           4  1/5/2017           32          4   Rain
5           5  1/6/2017           31          2  Sunny

In [83]:
df2.to_csv('file.csv')

In [84]:
df2.to_csv('file.csv', index=False)

In [88]:
d1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['coll', 'number'])
d2 = pd.DataFrame([['c', 3, 'lion'], ['d', 4, 'tiger']], columns=['letter', 'number', 'animal'])

In [89]:
d1

  coll  number
0    a       1
1    b       2

In [90]:
d2

  letter  number animal
0      c       3   lion
1      d       4  tiger

In [91]:
pd.concat([d1, d2], axis=0)

  coll  number letter animal
0    a       1    NaN    NaN
1    b       2    NaN    NaN
0  NaN       3      c   lion
1  NaN       4      d  tiger

In [92]:
pd.concat([d1, d2], axis=1)

  coll  number letter  number animal
0    a       1      c       3   lion
1    b       2      d       4  tiger

In [93]:
pd.concat([d1, d2], axis=0, ignore_index=True)

  coll  number letter animal
0    a       1    NaN    NaN
1    b       2    NaN    NaN
2  NaN       3      c   lion
3  NaN       4      d  tiger

In [94]:
df2 = pd.read_csv("weather_data.csv")

In [95]:
df2

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [96]:
df_group = df2.groupby("event")

In [97]:
df_group

In [99]:
for event in df_group:
    print(event)

('Rain',         day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain)
('Snow',         day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow)
('Sunny',         day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
5  1/6/2017           31          2  Sunny)

In [100]:
df_group.get_group("Rain")

        day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [102]:
df_group.describe()

      temperature                                               windspeed  \
            count  mean       std   min   25%   50%   75%   max     count
event
Rain          2.0  32.0  0.000000  32.0  32.0  32.0  32.0  32.0       2.0
Snow          2.0  26.0  2.828427  24.0  25.0  26.0  27.0  28.0       2.0
Sunny         2.0  33.0  2.828427  31.0  32.0  33.0  34.0  35.0       2.0


      mean       std  min   25%  50%   75%  max
event
Rain   5.0  1.414214  4.0  4.50  5.0  5.50  6.0
Snow   4.5  3.535534  2.0  3.25  4.5  5.75  7.0
Sunny  4.5  3.535534  2.0  3.25  4.5  5.75  7.0

In [103]:
def hot_temp(x):
    return x > 30

In [105]:
df2['hot_temp'] = df2['temperature'].apply(hot_temp)

df2

In [106]:
df2

        day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True

In [107]:
df2['hot_temp'] = df2['temperature'].apply(lambda x : x > 30)

In [108]:
df2

        day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True

In [109]:
d1 = pd.DataFrame({
    'city': ['lucknow', 'kanpur', 'agra', 'delhi'], 
    'temperature': [32, 45, 30, 40]
})

In [110]:
d1

      city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40

In [111]:
d2 = pd.DataFrame({
    'city': ['lucknow', 'kanpur', 'delhi'], 
    'humidity': [68, 65, 75]
})

In [112]:
d2

      city  humidity
0  lucknow        68
1   kanpur        65
2    delhi        75

In [113]:
df = pd.merge(d1, d2, on="city")

In [114]:
df

      city  temperature  humidity
0  lucknow           32        68
1   kanpur           45        65
2    delhi           40        75

In [115]:
pd.merge(d1, d2, on=['city'], how='outer')

      city  temperature  humidity
0  lucknow           32      68.0
1   kanpur           45      65.0
2     agra           30       NaN
3    delhi           40      75.0

In [116]:
pd.merge(d1, d2, on=['city'], how='left')

      city  temperature  humidity
0  lucknow           32      68.0
1   kanpur           45      65.0
2     agra           30       NaN
3    delhi           40      75.0

In [118]:
# Pivot table
df2.pivot_table(values='temperature', index='event', aggfunc = 'mean')

       temperature
event
Rain          32.0
Snow          26.0
Sunny         33.0

In [129]:
df2.pivot_table(columns = 'temperature', aggfunc='first')

temperature        24        28        31        32        35
day          1/4/2017  1/3/2017  1/6/2017  1/1/2017  1/2/2017
event            Snow      Snow     Sunny      Rain     Sunny
hot_temp        False     False      True      True      True
windspeed           7         2         2         6         7

In [130]:
df2.pivot_table(columns = 'temperature', values='windspeed')

temperature   24   28   31   32   35
windspeed    7.0  2.0  2.0  5.0  7.0

In [144]:
df2

          temperature  windspeed  event  hot_temp
day
1/1/2017           32          6   Rain      True
1/2/2017           35          7  Sunny      True
1/3/2017           28          2   Snow     False
1/4/2017           24          7   Snow     False
1/5/2017           32          4   Rain      True
1/6/2017           31          2  Sunny      True

In [135]:
df2.set_index('day', inplace=True)

In [137]:
df2.groupby('day'.dt.day)

AttributeError: 'str' object has no attribute 'dt'

In [145]:
df2.index = pd.to_datetime(df2.index)

In [146]:
df2

            temperature  windspeed  event  hot_temp
day
2017-01-01           32          6   Rain      True
2017-01-02           35          7  Sunny      True
2017-01-03           28          2   Snow     False
2017-01-04           24          7   Snow     False
2017-01-05           32          4   Rain      True
2017-01-06           31          2  Sunny      True

In [149]:
df2_grouped = df2.groupby(df2.index.day)

In [150]:
df2_grouped.describe()

    temperature                                         windspeed           \
          count  mean std   min   25%   50%   75%   max     count mean std
day
1           1.0  32.0 NaN  32.0  32.0  32.0  32.0  32.0       1.0  6.0 NaN
2           1.0  35.0 NaN  35.0  35.0  35.0  35.0  35.0       1.0  7.0 NaN
3           1.0  28.0 NaN  28.0  28.0  28.0  28.0  28.0       1.0  2.0 NaN
4           1.0  24.0 NaN  24.0  24.0  24.0  24.0  24.0       1.0  7.0 NaN
5           1.0  32.0 NaN  32.0  32.0  32.0  32.0  32.0       1.0  4.0 NaN
6           1.0  31.0 NaN  31.0  31.0  31.0  31.0  31.0       1.0  2.0 NaN


     min  25%  50%  75%  max
day
1    6.0  6.0  6.0  6.0  6.0
2    7.0  7.0  7.0  7.0  7.0
3    2.0  2.0  2.0  2.0  2.0
4    7.0  7.0  7.0  7.0  7.0
5    4.0  4.0  4.0  4.0  4.0
6    2.0  2.0  2.0  2.0  2.0